### ISSUE TITLE
Support for image rendering

### ISSUE THREAD

**Issue by RobertK66** [shrink/actions-document-publish#13]
Hi there,
your action is a great starting point for both: getting a  pdf documentation (out of multiple md files!) and learning and playing around with github actions in general as it reduces complexity by leveraging the other action from https://github.com/BaileyJM02/markdown-to-pdf 

My issue was, that I need image support. So I forked your repos and added some parameters to pass through to the underlying tool. In the end I also found a solution to issue #11 by adding a publish.css file and using the loop you discussed with @omeganot.

I know that you stated to go to the other project for more complex scenarios and maybe it would be feasible to ask for the ‘merge multiple md files into single pdf’ feature there, but for the moment I am perfectly happy with this solution here.  If you want, I can submit this changes ( https://github.com/RobertK66/actions-document-publish ) as a pull request and you can decide on integrating them into one of your next releases.

thx. and have fun
Robert

**Comment by shrink** [comment]
Thank you for sharing your thoughts and implementation, @RobertK66. As you identify, the emphasis of this action is on providing a very simple Markdown file(s) to single PDF implementation. That said, I think you're correct to identify image embed as a feature a user would reasonably expect _because_ it's a Markdown feature. I'll find some time in the coming days to implement support for images (using your fork as inspiration!) and report back on progress. My hope is that I can set the image root to the workspace root and so it'll work for all users without configuration, which seems to be possible looking at markdown-to-pdf's options + code.

Regarding the issue described in #11: I remain on the fence about adding this feature, and I don't want new features to be dictated by demand -- otherwise, the action will never be complete! That said, your fork's use of a stylesheet is very interesting and certainly provides a compelling example of how the action could remain focused (and therefore simple) while providing more depth for users who need it.

I'll do some more thinking about it and provide an update on that too. My gut feeling is that this is a very good idea. Thank you again for the thoughts and your implementation, very helpful and I look forward to seeing the positive impact your feedback has on the action!

**Comment by zhivkoangelov** [comment]
Any progress with the image rendering? That would be very useful feature. Thanks.

**Comment by shrink** [comment]
Hi @zhivkoangelov, thank you for the feedback on the proposed feature's usefulness to you, too. Unfortunately, I didn't find time to address this at the time of my previous comment, and it has taken a back seat to some other work since. That said, after further thinking, I agree that the feature should be a part of the action. I'll try to get to addressing this before the end of the week! Thank you for your patience :)

**Comment by shrink** [comment]
I'm closing this issue as I am archiving this GitHub Action (see #15). The Action will continue to work as-is, but no further changes will be made.
