### ISSUE TITLE
Stuck on action

### ISSUE THREAD

**Issue by AlexMohanMD** [shrink/actions-document-publish#8]
Getting stuck here: 

```
Run shrink/actions-document-publish@v1
6
/usr/bin/docker run --name c8ce414a4538b7784cc9b3f6051f7e48915b_d78eb0 --label 48c8ce --workdir /github/workspace --rm -e GITHUB_TOKEN -e INPUT_SOURCES -e HOME -e GITHUB_JOB -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_REPOSITORY_OWNER -e GITHUB_RUN_ID -e GITHUB_RUN_NUMBER -e GITHUB_RETENTION_DAYS -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_SERVER_URL -e GITHUB_API_URL -e GITHUB_GRAPHQL_URL -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e GITHUB_ACTION_REPOSITORY -e GITHUB_ACTION_REF -e GITHUB_PATH -e GITHUB_ENV -e RUNNER_OS -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e ACTIONS_CACHE_URL -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_c...
8
Started image server with image folder route '/github/workspace/.publish-docs/'.
9

10
Markdown files found: document.md
11
(node:14) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open '/github/workspace/.publish-docsdocument.md'
12
    at Object.openSync (fs.js:462:3)
13
    at Object.readFileSync (fs.js:364:35)
14
    at Function.getFileContent (/markdown-to-pdf.js:22:12)
15
    at GetFileBody (/github_interface.js:77:16)
16
    at /github_interface.js:139:33
17
    at FSReqCallback.oncomplete (fs.js:156:23)
18
(node:14) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
19
(node:14) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by shrink** [comment]
Hi @AlexanderMohan, apologies for the inconvenience. Do you have a link to the repository that this is in, or can you provide a copy of the GitHub Workflow definition that you're using? The error is indicating that there's an issue with the path missing a directory separator, so it could be a platform issue (are you running on `ubuntu-latest`?) -- but it could also be that there's an environment variable having an impact. A copy of the Workflow (or link to the repository) will help me track down the issue for you.

**Comment by AlexMohanMD** [comment]
Hi, have a look here: https://github.com/EdinburghUniversityTheatreCompany/Constitution

The action is in `.github/workflows/markdown-pdf.yml`

**Comment by shrink** [comment]
@AlexanderMohan Perfect, thank you for the link. At first glance I don't see an obvious issue, I'll investigate further now and get back to you today with an update. 

I built this action over a year ago before I had perfected the art of creating GitHub Actions so it's very possible there's an obvious error that I missed due to the absence of tests (unlike [the actions I've published more recently](https://github.com/pr-mpt) which are tested, I should probably fix up `actions-document-publish` at some point).

**Comment by AlexMohanMD** [comment]
Great, thanks for such a fast response - this will eventually be perfect for us to use so I'd love if there is a solution for this, thanks @shrink

**Comment by AlexMohanMD** [comment]
It seems like it would be an issue with input_sources but im not sure

**Comment by shrink** [comment]
@AlexanderMohan I've identified the issue. The upstream Markdown to PDF library has made some breaking changes, but due to the way I was depending on it -- not pinned to a version -- the breaking change broke this action. Entirely my fault!

I've just released a fix so if you re-run your Actions now they should work as expected. Sorry for the inconvenience! I'll add a rewrite of this action to my task list, not sure when I'll get to it though (but feel free to reach out again if you do encounter any new issues).
